### ISSUE TITLE
segmentation.m wrong dimension?

### ISSUE THREAD

**Issue by ghost** [StephanieRey/ABLE#1]
Line 219 of segmentation.m reads
           x_max                  = min(max(x_loc) + 2, video_dim(2));
and produces an error for me. It should probably read
           x_max                  = min(max(x_loc) + 2, video_dim(1));
? 

Thank you for a great toolbox!
J

**Comment by StephanieRey** [comment]
Thanks for pointing this out, I've altered the file accordingly.

Best,
Stepanie
